// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHjyGRFfRTNvfgaYP4ibFy8pMVXaQCIMs',
    appId: '1:60963203421:web:071db5856c223b66ace0b4',
    messagingSenderId: '60963203421',
    projectId: 'transports-aa595',
    authDomain: 'transports-aa595.firebaseapp.com',
    storageBucket: 'transports-aa595.firebasestorage.app',
    measurementId: 'G-129X1PJXN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDqP1k2wb7hUxXCJN7xPMu4WEk0kppWd8',
    appId: '1:60963203421:android:b2881ddb6a362127ace0b4',
    messagingSenderId: '60963203421',
    projectId: 'transports-aa595',
    storageBucket: 'transports-aa595.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfw5TDPGklPVTXRwV5MQZI8rIBPHQKX7w',
    appId: '1:60963203421:ios:487c6c2f24999c09ace0b4',
    messagingSenderId: '60963203421',
    projectId: 'transports-aa595',
    storageBucket: 'transports-aa595.firebasestorage.app',
    iosBundleId: 'deme.sn.transport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfw5TDPGklPVTXRwV5MQZI8rIBPHQKX7w',
    appId: '1:60963203421:ios:487c6c2f24999c09ace0b4',
    messagingSenderId: '60963203421',
    projectId: 'transports-aa595',
    storageBucket: 'transports-aa595.firebasestorage.app',
    iosBundleId: 'deme.sn.transport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHjyGRFfRTNvfgaYP4ibFy8pMVXaQCIMs',
    appId: '1:60963203421:web:2314911b54619b8face0b4',
    messagingSenderId: '60963203421',
    projectId: 'transports-aa595',
    authDomain: 'transports-aa595.firebaseapp.com',
    storageBucket: 'transports-aa595.firebasestorage.app',
    measurementId: 'G-R8DBRE17HV',
  );
}
